---
name: Pull Request
on:
  pull_request:
  merge_group:

jobs:
  basic:
    name: Display event
    runs-on: ubuntu-latest
    steps:

      - name: Display event
        run: |
          set +x
          echo '${{ toJson(github.event) }}' | jq .

...
